### ISSUE TITLE
return config/response

### ISSUE THREAD

**Issue by xenoterracide** [new10com/axios-logger#28]
instead of   
```ts
axiosInstance.interceptors.request.use(config => {
    axiosLogger.logRequest(config)
    return config
  })
  axiosInstance.interceptors.response.use(response => {
    axiosLogger.logResponse(response)
    return response
  })
```

```ts
  axiosInstance.interceptors.request.use(config => axiosLogger.logRequest(config))
  axiosInstance.interceptors.response.use(response => axiosLogger.logResponse(config))
```

**Comment by azakordonets** [comment]
Do you suggest to update documentation, or some changes in the code ?

**Comment by xenoterracide** [comment]
code, I'm suggesting that logRequest/logResponse should return their input instead of void, also any chance of fixing #4 and my recent update to #6 ;)

**Comment by azakordonets** [comment]
Regarding this issue - new version is published in `@new10com/axios-logger@0.2.1`. Give it a try. Regarding #4 I'm gonna need your input first, cuz I think I fixed it. Regarding #6 - can't say when I will be able to work on it. If you need it now, I suggest you to make a PR. Otherwise, I will do it when I have a chance. 

Thanks.

**Comment by xenoterracide** [comment]
looks good!

**Comment by xenoterracide** [comment]
hmm... I should have asked for error as well

**Comment by azakordonets** [comment]
@xenoterracide check 0.2.2 version :)
