### ISSUE TITLE
consider alternate output formats

### ISSUE THREAD

**Issue by xenoterracide** [new10com/axios-logger#6]
This isn't really a big deal to me, but copy and paste into other clients is nice (also, note to self, curl/wget should be able to take raw http...). 3 formats I'm considering

* HTTP - this should be the same output as an actual HTTP request that sends over the wire

because you might only have one...

* curl - so you can run it with the curl command
* wget - so you can run it with the wget command

**Comment by azakordonets** [comment]
I suppose that it would be nice to have curl/wget formats for request only ? :) In general i like the idea and in deed it could be helpful in case when you need to debug something. I will look into that as well. Thanks!

**Comment by xenoterracide** [comment]
the only reason I suggest the raw http, is intellij has an http templating feature https://www.jetbrains.com/help/idea/http-client-in-product-code-editor.html#using-response-handler-scripts which could be useful. honestly making this request I've considered opening issues for curl/wget to support it, as someone who started in OPS I'd rather deal with HTTP than trying to figure out obscure CLI options.

**Comment by xenoterracide** [comment]
So update here, at new job our requirement is that in production we log requests on a single line as json. A lot of log parser/analyzers need a json format on 1 line.

So it might be nice to have that feature, especially with the header sanitization since apparently, we're not doing that. For now I may context switch.

**Comment by azakordonets** [comment]
But, then for json format I suppose you would want to have some sort of JSON schema in order to be able to properly parse/analyze it, right ? I suppose that logging this in json format should not be difficult, but can't promise you about any deadlines because I have lot's of things going on right now. If it's very important to you and urgent - PR's are more then welcome. I don't read Github notifications on regular basis, so feel free to find my contact details on https://biercoff.com if you need me to review your PR right away.
